# Generated by Django 2.0.5 on 2018-05-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank=True, max_length=32, null=True)),
                ('system_type', models.CharField(blank=True, max_length=32, null=True)),
                ('system_version', models.CharField(blank=True, max_length=8, null=True)),
                ('system_arch', models.CharField(blank=True, max_length=16, null=True)),
                ('lan_ip', models.CharField(max_length=24, unique=True)),
                ('wan_ip', models.CharField(blank=True, max_length=64)),
                ('idc_id', models.IntegerField()),
                ('mac', models.CharField(blank=True, max_length=32, null=True)),
                ('kernel', models.CharField(blank=True, max_length=32, null=True)),
                ('kernel_version', models.CharField(blank=True, max_length=64, null=True)),
                ('cpu_model', models.CharField(blank=True, max_length=64, null=True)),
                ('cpu_num', models.CharField(blank=True, max_length=4, null=True)),
                ('memory', models.CharField(blank=True, max_length=128, null=True)),
                ('disk', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
