# Generated by Django 2.0.5 on 2018-05-16 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assets',
            options={'verbose_name': '资产', 'verbose_name_plural': '资产管理'},
        ),
    ]
